/** App routes that require a signed-in user (client-side AuthSessionGate). */
export const PROTECTED_ROUTE_PREFIXES = [
  "/dashboard",
  "/today",
  "/calendar",
  "/plants",
  "/scanner",
  "/learn",
  "/academy",
  "/database",
  "/settings",
  "/more",
  "/activity",
  "/beta-start",
  "/tester-guide",
  "/doctor",
  "/achievements",
  "/gallery",
  "/harvest",
  "/shop-assistant",
  "/property",
  "/collection",
  "/community",
  "/upgrade",
  "/billing",
  "/ar",
  "/price-checker",
  "/garden-map",
  "/design-studio",
  "/family",
  "/seasonal",
  "/missions",
  "/marketplace",
  "/landscape",
  "/landscape-designer",
  "/friends",
  "/invite",
  "/concierge",
  "/notifications",
] as const;

export function isProtectedRoute(pathname: string): boolean {
  return PROTECTED_ROUTE_PREFIXES.some((p) => pathname === p || pathname.startsWith(`${p}/`));
}
