import Link from "next/link";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/**
 * Planty: the PlantPal mascot. A friendly leaf inspired by the logo.
 * Helpful, slightly sarcastic, never a cartoon takeover.
 *
 * Usage rules (see /brand):
 * - Max one Planty per page.
 * - Small and subtle. Big only on empty or success states.
 * - Never on severe health warnings, expert review, legal, or payment pages.
 *
 * Matching PNG assets live in public/assets/mascot/ (planty-main.png,
 * planty-happy.png, ...) generated by scripts/generate-mascot.mjs.
 */

export type PlantyVariant =
  | "main"
  | "happy"
  | "thinking"
  | "diagnosing"
  | "niceWork"
  | "uhOh";

/** White line-art face. Designed to sit on the brand green tile. */
export function PlantyFaceSvg({
  variant = "main",
  className,
}: {
  variant?: PlantyVariant;
  className?: string;
}) {
  return (
    <svg viewBox="0 0 40 40" className={className} fill="none" aria-hidden>
      {/* Leaf body + stem */}
      <path
        d="M20 6C14 6 10 12 10 18c0 6 4 12 10 16 6-4 10-10 10-16 0-6-4-12-10-12z"
        stroke="white"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path d="M20 34V22" stroke="white" strokeWidth="2.5" strokeLinecap="round" />

      {variant === "happy" ? (
        <>
          <path d="M14 17.5q2-2.5 4 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <path d="M22 17.5q2-2.5 4 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <path d="M15.5 21.5q4.5 4 9 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
        </>
      ) : variant === "thinking" ? (
        <>
          <path d="M14.5 16.5l3 1" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <circle cx="24" cy="17" r="1.5" fill="white" />
          <path d="M17 22.5h6" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <circle cx="30" cy="10" r="1.2" fill="white" />
          <circle cx="33" cy="7" r="0.8" fill="white" />
        </>
      ) : variant === "diagnosing" ? (
        <>
          {/* Magnifying glass over one eye */}
          <circle cx="16" cy="17" r="3.4" stroke="white" strokeWidth="1.5" />
          <circle cx="16" cy="17" r="1.2" fill="white" />
          <path d="M18.6 19.6l2.6 2.6" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <circle cx="24.5" cy="16.5" r="1.5" fill="white" />
          <path d="M18 24.5q3 1.5 6 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
        </>
      ) : variant === "niceWork" ? (
        <>
          <path d="M14 17.5q2-2.5 4 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <path d="M22 17.5q2-2.5 4 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <path d="M15.5 21q4.5 4.5 9 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <circle cx="7" cy="9" r="1" fill="white" />
          <circle cx="33" cy="11" r="1" fill="white" />
          <circle cx="30" cy="5" r="0.8" fill="white" />
        </>
      ) : variant === "uhOh" ? (
        <>
          <circle cx="16" cy="17" r="1.5" fill="white" />
          <circle cx="24" cy="17" r="1.5" fill="white" />
          <path d="M16.5 23.5q3.5-2.5 7 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          <path d="M31 8q1.5 2.5 0 4" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
        </>
      ) : (
        <>
          <circle cx="16" cy="17" r="1.5" fill="white" />
          <circle cx="24" cy="17" r="1.5" fill="white" />
          <path d="M16 22q4 3 8 0" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
        </>
      )}
    </svg>
  );
}

const SIZE_PX = { sm: 40, md: 56, lg: 80 } as const;

export type PlantySize = keyof typeof SIZE_PX | number;

function resolveSize(size: PlantySize | undefined, subtle: boolean): number {
  if (typeof size === "number") return size;
  if (size) return SIZE_PX[size];
  return subtle ? SIZE_PX.sm : SIZE_PX.md;
}

/** The mascot avatar: green rounded tile + white face. No heavy shadow. */
export function PlantyAvatar({
  variant = "main",
  size = "md",
  className,
}: {
  variant?: PlantyVariant;
  size?: PlantySize;
  className?: string;
}) {
  const px = resolveSize(size, false);
  return (
    <div
      className={cn(
        "shrink-0 rounded-2xl bg-brand-primary flex items-center justify-center",
        className
      )}
      style={{ width: px, height: px }}
      aria-hidden
    >
      <PlantyFaceSvg variant={variant} className="w-[70%] h-[70%]" />
    </div>
  );
}

interface PlantyProps {
  variant?: PlantyVariant;
  size?: PlantySize;
  className?: string;
  /** Optional one-liner shown next to Planty in a soft callout. */
  message?: string;
  /** Smaller, quieter rendering for inline use. */
  subtle?: boolean;
}

/**
 * Planty with an optional message callout.
 * Without a message it renders just the avatar.
 */
export function Planty({
  variant = "main",
  size,
  className,
  message,
  subtle = false,
}: PlantyProps) {
  const px = resolveSize(size, subtle);

  if (!message) {
    return <PlantyAvatar variant={variant} size={px} className={className} />;
  }

  return (
    <div className={cn("flex items-center gap-3", className)}>
      <PlantyAvatar variant={variant} size={px} />
      <div
        className={cn(
          "rounded-2xl rounded-bl-sm px-4 py-2.5 text-left",
          subtle
            ? "bg-brand-sage/10 border border-brand-sage/20"
            : "bg-white border border-brand-sage/30 shadow-sm"
        )}
      >
        <p
          className={cn(
            "leading-snug text-brand-text",
            subtle ? "text-xs" : "text-sm"
          )}
        >
          {message}
        </p>
      </div>
    </div>
  );
}

/** "Planty says" tip box for blog posts and light in-app tips. */
export function PlantyTip({
  tip,
  className,
}: {
  tip: string;
  className?: string;
}) {
  return (
    <aside
      className={cn(
        "flex items-start gap-3 rounded-2xl bg-brand-sage/10 border border-brand-sage/25 p-4",
        className
      )}
    >
      <PlantyAvatar variant="happy" size="sm" />
      <div className="min-w-0">
        <p className="text-[10px] font-semibold uppercase tracking-wide text-brand-primary">
          Planty says
        </p>
        <p className="text-sm text-brand-text leading-relaxed mt-1">{tip}</p>
      </div>
    </aside>
  );
}

/** Centered Planty for empty states. The one place Planty gets to be big. */
export function PlantyEmptyState({
  variant = "happy",
  title,
  message,
  className,
  children,
}: {
  variant?: PlantyVariant;
  title: string;
  message?: string;
  className?: string;
  children?: React.ReactNode;
}) {
  return (
    <div className={cn("text-center", className)}>
      <PlantyAvatar variant={variant} size="lg" className="mx-auto" />
      <h2 className="text-xl font-bold text-gray-900 mt-4">{title}</h2>
      {message && (
        <p className="text-sm text-gray-500 mt-2 max-w-sm mx-auto leading-relaxed">
          {message}
        </p>
      )}
      {children}
    </div>
  );
}

/** Planty celebrating a win. */
export function PlantySuccess({
  message,
  className,
  size = "md",
}: {
  message: string;
  className?: string;
  size?: PlantySize;
}) {
  return (
    <Planty
      variant="niceWork"
      size={size}
      message={message}
      className={className}
    />
  );
}

/** Friendly error state. Not for severe plant health warnings. */
export function PlantyError({
  title = "That didn't work.",
  message = "Plants are dramatic. Apps are too.",
  retryLabel,
  onRetry,
  homeHref,
  homeLabel,
  className,
}: {
  title?: string;
  message?: string;
  retryLabel?: string;
  onRetry?: () => void;
  homeHref?: string;
  homeLabel?: string;
  className?: string;
}) {
  return (
    <div className={cn("text-center", className)}>
      <PlantyAvatar variant="uhOh" size="lg" className="mx-auto" />
      <h1 className="text-xl font-semibold text-gray-900 mt-4">{title}</h1>
      <p className="text-sm text-gray-500 mt-2 leading-relaxed">{message}</p>
      {(onRetry || homeHref) && (
        <div className="flex flex-col sm:flex-row gap-3 justify-center mt-6">
          {onRetry && <Button onClick={onRetry}>{retryLabel ?? "Try again"}</Button>}
          {homeHref && (
            <Link href={homeHref}>
              <Button variant="outline">{homeLabel ?? "Go home"}</Button>
            </Link>
          )}
        </div>
      )}
    </div>
  );
}
