/** Official PlantPal brand assets — always use these paths, never recreate the mark in SVG. */
export const OFFICIAL_APP_ICON = "/app-icon.png";

/** PWA / favicon paths (generated by scripts/generate-app-icons.mjs). */
export const APP_ICON_PATHS = {
  master: "/app-icon.png",
  svg: "/icon.svg",
  png512: "/icon-512.png",
  png192: "/icon-192.png",
  android512: "/android-chrome-512x512.png",
  android192: "/android-chrome-192x192.png",
  appleTouch: "/apple-touch-icon.png",
  favicon32: "/favicon-32x32.png",
  favicon16: "/favicon-16x16.png",
} as const;

export const BRAND = {
  name: "PlantPal",
  tagline: "Grow with confidence.",
  oneLiner:
    "PlantPal helps you track every plant, diagnose problems with photos, and get personalized care advice based on where you live.",
  positioning:
    "PlantPal is the smart plant care coach that helps homeowners, gardeners, and plant enthusiasts track, diagnose, and care for every plant they own using local climate intelligence, AI guidance, and personalized growing goals.",
  mission:
    "Help every homeowner, gardener, and plant parent grow healthier plants through simple, local, personalized guidance.",
  vision:
    "Become the operating system for plant ownership — where every plant has a digital twin, health profile, growth history, personalized care plan, local climate strategy, and goal-based roadmap.",
  promise:
    "PlantPal gives plant owners confidence — not more information, not more complexity.",
  appStoreDescription:
    "PlantPal is your smart plant care coach. Track every plant you own, diagnose problems with photos, get personalized care plans, receive local climate intelligence, and know exactly what to do each day. Whether you're growing houseplants, fruit trees, bonsai, vegetables, or a full backyard garden, PlantPal helps you grow with confidence.",
  colors: {
    primary: "#2D6A4F",
    sage: "#95B89B",
    growth: "#74C365",
    background: "#FAFBF8",
    text: "#1F2937",
    textSecondary: "#6B7280",
  },
  /** Official logo file — Living P squircle (PNG). Use for all UI, favicon, PWA. */
  officialIcon: OFFICIAL_APP_ICON,
} as const;
