import type { AcademyBadge } from "./types";

export const ACADEMY_BADGES: AcademyBadge[] = [
  {
    id: "first-plant",
    title: "First Plant",
    description: "Added your first plant to the garden.",
    icon: "🪴",
    category: "milestone",
    unlockKey: "plants:1",
    target: 1,
  },
  {
    id: "first-diagnosis",
    title: "First Diagnosis",
    description: "Completed your first plant health scan.",
    icon: "🔬",
    category: "care",
    unlockKey: "scans:1",
    target: 1,
  },
  {
    id: "fruit-tree-owner",
    title: "Fruit Tree Owner",
    description: "Added a fruit tree to your garden.",
    icon: "🍋",
    category: "collection",
    unlockKey: "fruit_tree",
  },
  {
    id: "bonsai-beginner",
    title: "Bonsai Beginner",
    description: "Completed the Bonsai learning path.",
    icon: "🌳",
    category: "learning",
    unlockKey: "path:bonsai",
  },
  {
    id: "compost-hero",
    title: "Compost Hero",
    description: "Finished Soil Mastery lessons.",
    icon: "♻️",
    category: "learning",
    unlockKey: "path:soil-mastery",
  },
  {
    id: "bug-hunter",
    title: "Bug Hunter",
    description: "Completed Garden Bugs lessons.",
    icon: "🐞",
    category: "learning",
    unlockKey: "path:garden-bugs",
  },
  {
    id: "water-master",
    title: "Water Master",
    description: "Completed Water Mastery lessons.",
    icon: "💧",
    category: "learning",
    unlockKey: "path:water-mastery",
  },
  {
    id: "plant-doctor",
    title: "Plant Doctor",
    description: "Completed Plant Health lessons.",
    icon: "🩺",
    category: "learning",
    unlockKey: "path:plant-health",
  },
  {
    id: "master-gardener",
    title: "Master Gardener",
    description: "Earned 5 Academy certificates.",
    icon: "🏅",
    category: "milestone",
    unlockKey: "certificates:5",
    target: 5,
  },
  {
    id: "botanical-expert",
    title: "Botanical Expert",
    description: "Reached Botanical Expert rank.",
    icon: "📚",
    category: "milestone",
    unlockKey: "rank:Botanical Expert",
  },
  {
    id: "plant-wizard",
    title: "Plant Wizard",
    description: "Reached the highest Academy rank.",
    icon: "✨",
    category: "milestone",
    unlockKey: "rank:Plant Wizard",
  },
  {
    id: "streak-7",
    title: "Week Warrior",
    description: "7-day learning streak.",
    icon: "🔥",
    category: "milestone",
    unlockKey: "streak:7",
    target: 7,
  },
  {
    id: "streak-30",
    title: "Monthly Master",
    description: "30-day learning streak.",
    icon: "🔥",
    category: "milestone",
    unlockKey: "streak:30",
    target: 30,
  },
  {
    id: "streak-100",
    title: "Century Grower",
    description: "100-day learning streak.",
    icon: "🔥",
    category: "milestone",
    unlockKey: "streak:100",
    target: 100,
  },
  {
    id: "first-lesson",
    title: "Curious Seedling",
    description: "Completed your first Academy lesson.",
    icon: "📖",
    category: "learning",
    unlockKey: "lessons:1",
    target: 1,
  },
  {
    id: "lessons-25",
    title: "Dedicated Learner",
    description: "Completed 25 Academy lessons.",
    icon: "📝",
    category: "learning",
    unlockKey: "lessons:25",
    target: 25,
  },
  {
    id: "family-champion",
    title: "Family Champion",
    description: "Top of the family leaderboard this week.",
    icon: "👨‍👩‍👧",
    category: "family",
    unlockKey: "family_leader",
  },
];

export function getBadgeById(id: string): AcademyBadge | undefined {
  return ACADEMY_BADGES.find((b) => b.id === id);
}
