import type { Disease } from "../types";

const IMG = "https://images.unsplash.com/photo-1416879595882-337324a7f4f9?w=400&h=300&fit=crop&q=80";

export const DISEASES: Disease[] = [
  { id: "dis-root-rot", name: "Root rot", description: "Fungal decay of roots from prolonged soggy soil.", symptoms: "Yellowing, wilting despite wet soil, mushy roots", causes: "Overwatering, poor drainage, compacted soil", affected_plants: "Houseplants, succulents, trees in wet sites", treatment: "Repot in fresh mix; trim rotten roots; fungicide drench", prevention: "Well-draining soil; water only when needed", image_url: IMG },
  { id: "dis-powdery-mildew", name: "Powdery mildew", description: "White powdery fungal coating on leaf surfaces.", symptoms: "White dusty patches on leaves and stems", causes: "High humidity, poor airflow, shade", affected_plants: "Squash, roses, grapes, peonies", treatment: "Neem, potassium bicarbonate, sulfur spray", prevention: "Space plants; morning watering; resistant varieties", image_url: IMG },
  { id: "dis-leaf-spot", name: "Leaf spot", description: "Fungal or bacterial spots on foliage.", symptoms: "Brown or black circular spots, yellow halos", causes: "Splashing water, wet foliage, infected debris", affected_plants: "Tomatoes, hydrangeas, many ornamentals", treatment: "Remove affected leaves; copper fungicide", prevention: "Drip irrigation; sanitize tools", image_url: IMG },
  { id: "dis-rust", name: "Rust", description: "Orange/rust-colored fungal pustules on leaf undersides.", symptoms: "Orange powdery spots, premature leaf drop", causes: "Moist leaves, cool nights, spores from debris", affected_plants: "Roses, hollyhocks, beans, daylilies", treatment: "Remove infected leaves; fungicide early season", prevention: "Clean fall debris; improve air circulation", image_url: IMG },
  { id: "dis-blight", name: "Blight", description: "Rapid browning and collapse of leaves and stems.", symptoms: "Dark lesions spreading quickly, plant collapse", causes: "Wet weather, infected seed, soil splash", affected_plants: "Tomatoes, potatoes, peppers", treatment: "Remove infected tissue; copper or chlorothalonil", prevention: "Rotate crops; stake plants; resistant cultivars", image_url: IMG },
  { id: "dis-citrus-greening", name: "Citrus greening", description: "Bacterial disease spread by Asian citrus psyllid.", symptoms: "Asymmetric yellow mottling, bitter misshapen fruit", causes: "Candidatus Liberibacter; psyllid vector", affected_plants: "All citrus species", treatment: "No cure. Remove tree to protect neighbors", prevention: "Control psyllids; buy certified disease-free stock", image_url: IMG },
  { id: "dis-anthracnose", name: "Anthracnose", description: "Fungal disease causing sunken lesions on leaves and fruit.", symptoms: "Dark sunken spots, twig dieback", causes: "Wet spring weather, spores on debris", affected_plants: "Dogwood, sycamore, tomatoes, avocados", treatment: "Prune infected wood; fungicide at bud break", prevention: "Rake fallen leaves; avoid overhead irrigation", image_url: IMG },
  { id: "dis-fire-blight", name: "Fire blight", description: "Bacterial disease that blackens blossoms and shoots.", symptoms: "Blackened hook-shaped shoots, oozing cankers", causes: "Erwinia amylovora; warm wet bloom weather", affected_plants: "Apple, pear, crabapple, pyracantha", treatment: "Prune 12 in below infection in dry weather", prevention: "Avoid high-nitrogen spring feed; resistant varieties", image_url: IMG },
  { id: "dis-botrytis", name: "Botrytis (gray mold)", description: "Gray fuzzy mold on flowers and soft tissue.", symptoms: "Gray mold on blooms, soft rotting tissue", causes: "Cool humid conditions, dead plant material", affected_plants: "Strawberries, roses, geraniums, lettuce", treatment: "Remove affected parts; improve airflow; fungicide", prevention: "Deadhead; avoid crowding; reduce humidity indoors", image_url: IMG },
  { id: "dis-downy-mildew", name: "Downy mildew", description: "Fuzzy gray growth on leaf undersides.", symptoms: "Yellow patches on top, gray fuzz below", causes: "Cool wet nights, high humidity", affected_plants: "Impatiens, basil, cucumbers, grapes", treatment: "Fungicide labeled for downy mildew; remove plants", prevention: "Resistant varieties; avoid evening watering", image_url: IMG },
  { id: "dis-verticillium", name: "Verticillium wilt", description: "Soil-borne fungus blocking water transport.", symptoms: "One-sided wilting, brown streaks in vascular tissue", causes: "Verticillium in soil; persists for years", affected_plants: "Maple, tomato, eggplant, stone fruits", treatment: "No cure. Remove plant; solarize soil if possible", prevention: "Crop rotation; resistant rootstocks", image_url: IMG },
  { id: "dis-black-spot", name: "Black spot", description: "Common rose fungal disease.", symptoms: "Black spots with yellow halos, defoliation", causes: "Splashing water, warm humid weather", affected_plants: "Roses primarily", treatment: "Remove fallen leaves; fungicide program", prevention: "Plant resistant cultivars; mulch under roses", image_url: IMG },
  { id: "dis-blossom-end-rot", name: "Blossom end rot", description: "Calcium deficiency disorder on fruit, not a pathogen.", symptoms: "Dark leathery patch on blossom end of fruit", causes: "Calcium uptake blocked by irregular watering", affected_plants: "Tomatoes, peppers, squash", treatment: "Consistent watering; calcium foliar spray if needed", prevention: "Mulch; avoid drought stress", image_url: IMG },
  { id: "dis-crown-rot", name: "Crown rot", description: "Rot at base of plant from soil-line moisture.", symptoms: "Collapse at crown, foul-smelling base", causes: "Deep planting, mulch against stem, poor drainage", affected_plants: "Strawberries, succulents, trees", treatment: "Improve drainage; fungicide; may need replacement", prevention: "Plant at correct depth; keep mulch away from stem", image_url: IMG },
  { id: "dis-mosaic-virus", name: "Mosaic virus", description: "Viral infection causing mottled leaf patterns.", symptoms: "Mottled yellow-green leaves, stunted growth", causes: "Aphids, seeds, infected tools", affected_plants: "Tomatoes, cucumbers, many ornamentals", treatment: "Remove infected plants; control vectors", prevention: "Virus-free seed; sanitize tools; weed hosts", image_url: IMG },
];
