import type { Fertilizer } from "../types";

export const FERTILIZERS: Fertilizer[] = [
  { id: "fert-citrus", name: "Citrus fertilizer", type: "granular", npk_ratio: "8-8-8", best_for: "Citrus trees", application_frequency: "Every 6–8 weeks in growing season", season: "Spring through fall", warning_notes: "Avoid trunk contact; water in well", description: "Balanced feed with micronutrients for citrus." },
  { id: "fert-all-purpose", name: "All-purpose 10-10-10", type: "granular", npk_ratio: "10-10-10", best_for: "General garden beds", application_frequency: "Monthly during growth", season: "Spring and summer", warning_notes: "Do not over-apply — causes salt burn", description: "Standard balanced synthetic fertilizer." },
  { id: "fert-fish", name: "Fish emulsion", type: "liquid", npk_ratio: "5-1-1", best_for: "Leafy greens, houseplants", application_frequency: "Every 2–4 weeks", season: "Growing season", warning_notes: "Strong odor; dilute per label", description: "Organic nitrogen boost from fish byproducts." },
  { id: "fert-bone", name: "Bone meal", type: "organic", npk_ratio: "3-15-0", best_for: "Bulbs, roses, root crops", application_frequency: "At planting and once mid-season", season: "Spring", warning_notes: "Attracts dogs if surface-applied", description: "Slow-release phosphorus for roots and blooms." },
  { id: "fert-blood", name: "Blood meal", type: "organic", npk_ratio: "12-0-0", best_for: "Nitrogen-hungry vegetables", application_frequency: "Every 4–6 weeks", season: "Spring and summer", warning_notes: "Can burn roots if over-applied", description: "Fast-acting organic nitrogen source." },
  { id: "fert-compost", name: "Compost", type: "organic", npk_ratio: "2-1-1", best_for: "All plants as soil amendment", application_frequency: "1–2× per year top-dress", season: "Spring and fall", warning_notes: "Ensure compost is fully finished", description: "Builds soil biology and gentle nutrients." },
  { id: "fert-worm", name: "Worm castings", type: "organic", npk_ratio: "1-0-0", best_for: "Seedlings, houseplants, vegetables", application_frequency: "Every 4–6 weeks light dose", season: "Year-round indoors", warning_notes: "Low burn risk; safe for most plants", description: "Premium organic amendment with microbes." },
  { id: "fert-palm", name: "Palm fertilizer", type: "slow_release", npk_ratio: "8-2-12", best_for: "Palms", application_frequency: "Every 3 months", season: "Warm months", warning_notes: "Include magnesium and manganese", description: "Formulated for palm frond health." },
  { id: "fert-rose", name: "Rose fertilizer", type: "granular", npk_ratio: "6-12-6", best_for: "Roses and flowering shrubs", application_frequency: "Every 4–6 weeks", season: "Spring through first frost", warning_notes: "Stop feeding 6 weeks before frost", description: "Promotes blooms and strong canes." },
  { id: "fert-succulent", name: "Succulent fertilizer", type: "liquid", npk_ratio: "2-7-7", best_for: "Succulents and cacti", application_frequency: "Monthly in summer only", season: "Summer", warning_notes: "Do not feed dormant plants", description: "Low-nitrogen formula to prevent stretching." },
  { id: "fert-tomato", name: "Tomato fertilizer", type: "granular", npk_ratio: "5-10-10", best_for: "Tomatoes, peppers, eggplants", application_frequency: "Every 2 weeks after fruit set", season: "Summer", warning_notes: "Calcium helps prevent blossom end rot", description: "Phosphorus-heavy for fruit production." },
  { id: "fert-acid", name: "Acid-loving plant food", type: "liquid", npk_ratio: "30-10-10", best_for: "Azaleas, blueberries, camellias", application_frequency: "Every 2 weeks in growth", season: "Spring and early summer", warning_notes: "Only for acid-preferring plants", description: "Maintains low soil pH while feeding." },
  { id: "fert-lawn", name: "Lawn fertilizer", type: "granular", npk_ratio: "24-0-6", best_for: "Ornamental grasses, lawns", application_frequency: "Seasonal per grass type", season: "Spring and fall", warning_notes: "Keep off hardscapes — stains", description: "High nitrogen for green growth." },
  { id: "fert-orchid", name: "Orchid fertilizer", type: "liquid", npk_ratio: "20-20-20", best_for: "Orchids", application_frequency: "Weekly weakly (¼ strength)", season: "Year-round light feed", warning_notes: "Flush with plain water monthly", description: "Dilute balanced feed for epiphytes." },
  { id: "fert-kelp", name: "Kelp meal", type: "organic", npk_ratio: "1-0-2", best_for: "Transplant stress, seedlings", application_frequency: "At transplant and monthly", season: "Growing season", warning_notes: "Complements not replaces NPK", description: "Seaweed-derived growth stimulant." },
  { id: "fert-calcium", name: "Calcium nitrate", type: "synthetic", npk_ratio: "15-0-0", best_for: "Tomatoes, apples, brassicas", application_frequency: "As needed when deficiency shows", season: "Active growth", warning_notes: "Do not mix with phosphorus fertilizers", description: "Corrects calcium deficiency and tip burn." },
  { id: "fert-magnesium", name: "Epsom salt (magnesium)", type: "organic", npk_ratio: "0-0-0", best_for: "Tomatoes, roses, citrus", application_frequency: "Monthly foliar or soil drench", season: "Growing season", warning_notes: "Supplement only — not complete fertilizer", description: "Magnesium sulfate for chlorosis." },
  { id: "fert-hydro", name: "Hydroponic nutrient mix", type: "liquid", npk_ratio: "5-15-14", best_for: "Hydroponic herbs and vegetables", application_frequency: "Per reservoir schedule", season: "Year-round indoors", warning_notes: "Monitor EC and pH", description: "Complete macro and micronutrient solution." },
  { id: "fert-bloom", name: "Bloom booster", type: "liquid", npk_ratio: "10-30-20", best_for: "Annual flowers, containers", application_frequency: "Every 2 weeks pre-bloom", season: "Late spring through summer", warning_notes: "High phosphorus — not for seedlings", description: "Encourages bud formation and color." },
  { id: "fert-slow", name: "Osmocote slow-release", type: "slow_release", npk_ratio: "14-14-14", best_for: "Containers, shrubs", application_frequency: "Every 4–6 months", season: "Spring application", warning_notes: "Do not exceed label rate", description: "Coated granules release over months." },
];
