import type { Fertilizer } from "../types";

function fert(
  base: Omit<Fertilizer, "usage"> & { usage?: string }
): Fertilizer {
  return {
    usage: base.usage ?? "Apply per label directions; water in after granular applications",
    ...base,
  };
}

export const FERTILIZERS: Fertilizer[] = [
  fert({
    id: "fert-citrus",
    name: "Citrus fertilizer",
    type: "granular",
    npk_ratio: "8-8-8",
    best_for: "Citrus trees, lemons, limes, oranges",
    application_frequency: "Every 6–8 weeks in growing season",
    usage: "Spread evenly under drip line; water deeply after application; avoid trunk contact",
    season: "Spring through fall",
    warning_notes: "Avoid trunk contact; water in well",
    description: "Balanced feed with micronutrients (iron, zinc, manganese) for citrus.",
  }),
  fert({
    id: "fert-all-purpose",
    name: "All-purpose 10-10-10",
    type: "synthetic",
    npk_ratio: "10-10-10",
    best_for: "General garden beds, shrubs, lawns",
    application_frequency: "Monthly during growth",
    usage: "Broadcast granular at recommended rate; incorporate lightly into soil; irrigate after",
    season: "Spring and summer",
    warning_notes: "Do not over-apply — causes salt burn",
    description: "Standard balanced synthetic fertilizer for general use.",
  }),
  fert({
    id: "fert-fish",
    name: "Fish emulsion",
    type: "organic",
    npk_ratio: "5-1-1",
    best_for: "Leafy greens, houseplants, seedlings",
    application_frequency: "Every 2–4 weeks",
    usage: "Dilute with water (typically 1–2 tbsp per gallon); apply to soil or as foliar feed",
    season: "Growing season",
    warning_notes: "Strong odor; dilute per label",
    description: "Organic nitrogen boost from fish byproducts.",
  }),
  fert({
    id: "fert-bone",
    name: "Bone meal",
    type: "organic",
    npk_ratio: "3-15-0",
    best_for: "Bulbs, roses, root crops",
    application_frequency: "At planting and once mid-season",
    usage: "Mix into planting hole or top-dress and water in; slow-release phosphorus source",
    season: "Spring",
    warning_notes: "Attracts dogs if surface-applied",
    description: "Slow-release phosphorus for roots and blooms.",
  }),
  fert({
    id: "fert-blood",
    name: "Blood meal",
    type: "organic",
    npk_ratio: "12-0-0",
    best_for: "Nitrogen-hungry vegetables",
    application_frequency: "Every 4–6 weeks",
    usage: "Side-dress along rows or mix into top inch of soil; water in immediately",
    season: "Spring and summer",
    warning_notes: "Can burn roots if over-applied",
    description: "Fast-acting organic nitrogen source.",
  }),
  fert({
    id: "fert-compost",
    name: "Compost",
    type: "organic",
    npk_ratio: "2-1-1",
    best_for: "All plants as soil amendment",
    application_frequency: "1–2× per year top-dress",
    usage: "Spread 1–2 inches as mulch or incorporate into beds; no dilution needed",
    season: "Spring and fall",
    warning_notes: "Ensure compost is fully finished",
    description: "Builds soil biology and gentle nutrients.",
  }),
  fert({
    id: "fert-worm",
    name: "Worm castings",
    type: "organic",
    npk_ratio: "1-0-0",
    best_for: "Seedlings, houseplants, vegetables",
    application_frequency: "Every 4–6 weeks light dose",
    usage: "Top-dress containers or mix into potting soil at 10–20% by volume",
    season: "Year-round indoors",
    warning_notes: "Low burn risk; safe for most plants",
    description: "Premium organic amendment with microbes.",
  }),
  fert({
    id: "fert-palm",
    name: "Palm fertilizer",
    type: "slow_release",
    npk_ratio: "8-2-12",
    best_for: "Palms",
    application_frequency: "Every 3 months",
    usage: "Apply slow-release granules around root zone; include magnesium supplement if needed",
    season: "Warm months",
    warning_notes: "Include magnesium and manganese",
    description: "Formulated for palm frond health.",
  }),
  fert({
    id: "fert-rose",
    name: "Rose fertilizer",
    type: "granular",
    npk_ratio: "6-12-6",
    best_for: "Roses and flowering shrubs",
    application_frequency: "Every 4–6 weeks",
    usage: "Apply around base, scratch into soil surface, water in; stop 6 weeks before frost",
    season: "Spring through first frost",
    warning_notes: "Stop feeding 6 weeks before frost",
    description: "Promotes blooms and strong canes.",
  }),
  fert({
    id: "fert-bonsai",
    name: "Bonsai fertilizer",
    type: "liquid",
    npk_ratio: "7-6-4",
    best_for: "Bonsai, miniature trees",
    application_frequency: "Weekly at half strength during growth",
    usage: "Dilute liquid feed; apply during watering; reduce in dormancy",
    season: "Growing season only",
    warning_notes: "Never over-fertilize shallow bonsai pots",
    description: "Balanced liquid feed for controlled growth in small containers.",
  }),
  fert({
    id: "fert-succulent",
    name: "Succulent fertilizer",
    type: "liquid",
    npk_ratio: "2-7-7",
    best_for: "Succulents and cacti",
    application_frequency: "Monthly in summer only",
    usage: "Dilute heavily; apply to moist soil in morning; skip dormant months",
    season: "Summer",
    warning_notes: "Do not feed dormant plants",
    description: "Low-nitrogen formula to prevent stretching.",
  }),
  fert({
    id: "fert-tomato",
    name: "Tomato & vegetable fertilizer",
    type: "granular",
    npk_ratio: "5-10-10",
    best_for: "Tomatoes, peppers, eggplants, vegetables",
    application_frequency: "Every 2 weeks after fruit set",
    usage: "Side-dress when first fruits form; water in; calcium supplement helps prevent blossom end rot",
    season: "Summer",
    warning_notes: "Calcium helps prevent blossom end rot",
    description: "Phosphorus-heavy for fruit production.",
  }),
  fert({
    id: "fert-acid",
    name: "Acid-loving plant food",
    type: "liquid",
    npk_ratio: "30-10-10",
    best_for: "Azaleas, blueberries, camellias",
    application_frequency: "Every 2 weeks in growth",
    usage: "Dilute and apply to acid soil; avoid alkaline water if possible",
    season: "Spring and early summer",
    warning_notes: "Only for acid-preferring plants",
    description: "Maintains low soil pH while feeding.",
  }),
  fert({
    id: "fert-lawn",
    name: "Lawn fertilizer",
    type: "synthetic",
    npk_ratio: "24-0-6",
    best_for: "Ornamental grasses, lawns",
    application_frequency: "Seasonal per grass type",
    usage: "Broadcast with spreader; water in within 24 hours; keep off hardscapes",
    season: "Spring and fall",
    warning_notes: "Keep off hardscapes — stains",
    description: "High nitrogen for green growth.",
  }),
  fert({
    id: "fert-orchid",
    name: "Orchid fertilizer",
    type: "liquid",
    npk_ratio: "20-20-20",
    best_for: "Orchids",
    application_frequency: "Weekly weakly (¼ strength)",
    usage: "Dilute to quarter strength; pour through bark mix; flush with plain water monthly",
    season: "Year-round light feed",
    warning_notes: "Flush with plain water monthly",
    description: "Dilute balanced feed for epiphytes.",
  }),
  fert({
    id: "fert-kelp",
    name: "Kelp meal",
    type: "organic",
    npk_ratio: "1-0-2",
    best_for: "Transplant stress, seedlings",
    application_frequency: "At transplant and monthly",
    usage: "Mix into soil at planting or use as liquid kelp extract foliar spray",
    season: "Growing season",
    warning_notes: "Complements not replaces NPK",
    description: "Seaweed-derived growth stimulant.",
  }),
  fert({
    id: "fert-calcium",
    name: "Calcium nitrate",
    type: "synthetic",
    npk_ratio: "15-0-0",
    best_for: "Tomatoes, apples, brassicas",
    application_frequency: "As needed when deficiency shows",
    usage: "Dissolve in water for soil drench or foliar spray on lower leaves",
    season: "Active growth",
    warning_notes: "Do not mix with phosphorus fertilizers",
    description: "Corrects calcium deficiency and tip burn.",
  }),
  fert({
    id: "fert-magnesium",
    name: "Epsom salt (magnesium)",
    type: "organic",
    npk_ratio: "0-0-0",
    best_for: "Tomatoes, roses, citrus",
    application_frequency: "Monthly foliar or soil drench",
    usage: "1 tbsp per gallon water; spray foliage or drench root zone",
    season: "Growing season",
    warning_notes: "Supplement only — not complete fertilizer",
    description: "Magnesium sulfate for chlorosis.",
  }),
  fert({
    id: "fert-hydro",
    name: "Hydroponic nutrient mix",
    type: "liquid",
    npk_ratio: "5-15-14",
    best_for: "Hydroponic herbs and vegetables",
    application_frequency: "Per reservoir schedule",
    usage: "Mix into reservoir per EC target; monitor pH 5.5–6.5",
    season: "Year-round indoors",
    warning_notes: "Monitor EC and pH",
    description: "Complete macro and micronutrient solution.",
  }),
  fert({
    id: "fert-bloom",
    name: "Bloom booster",
    type: "liquid",
    npk_ratio: "10-30-20",
    best_for: "Annual flowers, containers",
    application_frequency: "Every 2 weeks pre-bloom",
    usage: "Dilute and apply when buds form; switch from high-nitrogen feed",
    season: "Late spring through summer",
    warning_notes: "High phosphorus — not for seedlings",
    description: "Encourages bud formation and color.",
  }),
  fert({
    id: "fert-slow",
    name: "Osmocote slow-release",
    type: "slow_release",
    npk_ratio: "14-14-14",
    best_for: "Containers, shrubs",
    application_frequency: "Every 4–6 months",
    usage: "Mix into top layer of potting soil or scratch into soil surface once per season",
    season: "Spring application",
    warning_notes: "Do not exceed label rate",
    description: "Coated granules release nutrients over months.",
  }),
];
