import type { Pest } from "../types";

const IMG = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=400&h=300&fit=crop&q=80`;

export const PESTS: Pest[] = [
  { id: "pest-aphids", name: "Aphids", description: "Soft-bodied sap-sucking insects that cluster on new growth.", signs: "Curled leaves, sticky honeydew, black sooty mold", affected_plants: "Roses, citrus, vegetables, houseplants", treatment: "Spray with insecticidal soap or neem oil; blast with water", prevention: "Encourage ladybugs; avoid over-fertilizing with nitrogen", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-spider-mites", name: "Spider mites", description: "Tiny arachnids that pierce leaf cells, thriving in dry heat.", signs: "Fine webbing, stippled yellow leaves", affected_plants: "Tomatoes, ivy, fruit trees, indoor plants", treatment: "Increase humidity; miticide or neem every 3–5 days", prevention: "Regular misting; isolate new plants", image_url: IMG("1466692476860-a088c219fe7a") },
  { id: "pest-scale", name: "Scale", description: "Armored or soft scale insects attached to stems and leaves.", signs: "Brown bumps, yellowing, sticky residue", affected_plants: "Citrus, ficus, orchids, palms", treatment: "Rub off with alcohol swab; horticultural oil sprays", prevention: "Inspect purchases; quarantine new plants", image_url: IMG("1509420437566-6041aa63f822") },
  { id: "pest-mealybugs", name: "Mealybugs", description: "White cottony pests hiding in leaf axils and soil line.", signs: "White fuzz clusters, stunted growth", affected_plants: "Succulents, tropical houseplants, citrus", treatment: "Q-tip with alcohol; systemic insecticide for severe cases", prevention: "Avoid overwatering; good airflow", image_url: IMG("1459411550354-917410133b27") },
  { id: "pest-whiteflies", name: "Whiteflies", description: "Small white flying insects on leaf undersides.", signs: "Cloud of flies when plant is disturbed", affected_plants: "Tomatoes, hibiscus, poinsettia, citrus", treatment: "Yellow sticky traps; insecticidal soap", prevention: "Remove heavily infested leaves early", image_url: IMG("1592150628122-0e8b6a11a6b0") },
  { id: "pest-fungus-gnats", name: "Fungus gnats", description: "Small flies whose larvae feed on wet organic soil.", signs: "Tiny flies around soil; larvae in top inch of soil", affected_plants: "Overwatered houseplants, seedlings", treatment: "Let soil dry; BTI drench; sticky traps", prevention: "Avoid soggy soil; top dress with sand", image_url: IMG("1558618666-fcd25c85cd64") },
  { id: "pest-thrips", name: "Thrips", description: "Slender insects that scrape leaf tissue leaving silvery scars.", signs: "Silvery streaks, distorted buds, black specks", affected_plants: "Roses, onions, gladiolus, many ornamentals", treatment: "Spinosad or neem; remove affected flowers", prevention: "Reflective mulch in vegetable beds", image_url: IMG("1593691502-6c263a056f09") },
  { id: "pest-caterpillars", name: "Caterpillars", description: "Larval stage of moths and butterflies that chew foliage.", signs: "Holes in leaves, frass (droppings), visible larvae", affected_plants: "Brassicas, tomatoes, fruit trees", treatment: "Hand-pick; Bt (Bacillus thuringiensis) spray", prevention: "Row covers on seedlings", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-slugs", name: "Slugs and snails", description: "Moisture-loving mollusks active at night.", signs: "Irregular holes, slime trails", affected_plants: "Hostas, lettuce, strawberries", treatment: "Beer traps, iron phosphate bait, hand pick at dusk", prevention: "Reduce mulch moisture; copper barriers", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-leafminers", name: "Leaf miners", description: "Larvae tunnel between leaf layers leaving visible trails.", signs: "Serpentine white trails in leaves", affected_plants: "Citrus, spinach, beets, ornamentals", treatment: "Remove affected leaves; spinosad for severe cases", prevention: "Monitor early; avoid over-head watering", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-japanese-beetle", name: "Japanese beetles", description: "Metallic green beetles that skeletonize leaves.", signs: "Lacy damaged leaves, beetles on flowers", affected_plants: "Roses, grapes, raspberries, linden", treatment: "Hand pick into soapy water; neem on early larvae", prevention: "Grub control in lawn if recurring", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-ants", name: "Ants (farming pests)", description: "Ants protect aphids and scale for honeydew.", signs: "Ant trails on stems; paired with sap-suckers", affected_plants: "Citrus, peonies, many garden plants", treatment: "Control underlying pest; ant baits at trails", prevention: "Sticky barriers on tree trunks", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-cutworm", name: "Cutworms", description: "Soil-dwelling larvae that cut seedlings at soil line.", signs: "Seedlings fallen over, severed at base", affected_plants: "Tomatoes, peppers, young transplants", treatment: "Collars around stems; hunt at night", prevention: "Clear debris; rotate crops", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-borer", name: "Stem borers", description: "Larvae tunnel into stems causing wilting.", signs: "Entry holes, frass, sudden branch wilt", affected_plants: "Squash, roses, fruit trees", treatment: "Slit stem to remove larva; destroy affected stems", prevention: "Remove plant debris; trap crops", image_url: IMG("1416879595882-337324a7f4f9") },
  { id: "pest-mosaic-virus-vector", name: "Whitefly & aphid (virus vectors)", description: "Sap feeders that spread viral diseases between plants.", signs: "Mottled leaves plus insect presence", affected_plants: "Tomatoes, peppers, cucurbits", treatment: "Remove infected plants; control vectors", prevention: "Resistant varieties; reflective mulch", image_url: IMG("1416879595882-337324a7f4f9") },
];
