import type { PlantSpecies, PlantSpeciesType } from "../types";
import {
  defaultCompanionPlants,
  defaultPollinatorValue,
  defaultFruitingInfo,
  defaultFloweringInfo,
} from "../defaults";

const IMG = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=600&h=400&fit=crop&q=80`;

type PartialSpecies = Pick<PlantSpecies, "common_name" | "scientific_name" | "type"> &
  Partial<Omit<PlantSpecies, "common_name" | "scientific_name" | "type">>;

let counter = 0;

export function makeSpecies(p: PartialSpecies): PlantSpecies {
  counter += 1;
  const defaults: Record<PlantSpeciesType, Partial<PlantSpecies>> = {
    tree: {
      sunlight: "Full sun (6+ hours)",
      watering: "Deep water weekly; more in summer",
      soil_preference: "Well-draining loam",
      hardiness_zone_min: 7,
      hardiness_zone_max: 10,
      mature_height: "15–25 ft",
      mature_width: "10–15 ft",
      growth_rate: "Moderate",
      maintenance_level: "Moderate",
    },
    shrub: {
      sunlight: "Full sun to partial shade",
      watering: "Water when top inch of soil is dry",
      soil_preference: "Rich, well-draining soil",
      hardiness_zone_min: 5,
      hardiness_zone_max: 9,
      mature_height: "3–6 ft",
      mature_width: "3–5 ft",
      growth_rate: "Moderate",
      maintenance_level: "Low to moderate",
    },
    flower: {
      sunlight: "Full sun",
      watering: "Keep soil evenly moist",
      soil_preference: "Loamy, fertile soil",
      hardiness_zone_min: 4,
      hardiness_zone_max: 9,
      mature_height: "1–3 ft",
      mature_width: "1–2 ft",
      growth_rate: "Fast",
      maintenance_level: "Moderate",
    },
    vegetable: {
      sunlight: "Full sun (6–8 hours)",
      watering: "Consistent moisture; avoid wet foliage",
      soil_preference: "Rich, well-draining garden soil",
      hardiness_zone_min: 3,
      hardiness_zone_max: 10,
      mature_height: "2–4 ft",
      mature_width: "2–3 ft",
      growth_rate: "Fast",
      maintenance_level: "Moderate",
    },
    herb: {
      sunlight: "Full sun",
      watering: "Allow soil to dry slightly between waterings",
      soil_preference: "Light, well-draining soil",
      hardiness_zone_min: 5,
      hardiness_zone_max: 10,
      mature_height: "1–2 ft",
      mature_width: "1–2 ft",
      growth_rate: "Fast",
      maintenance_level: "Low",
    },
    indoor: {
      sunlight: "Bright indirect light",
      watering: "Water when top 2 inches dry",
      soil_preference: "Quality potting mix",
      hardiness_zone_min: 10,
      hardiness_zone_max: 12,
      mature_height: "2–6 ft indoors",
      mature_width: "2–4 ft",
      growth_rate: "Slow to moderate",
      maintenance_level: "Low",
    },
    succulent: {
      sunlight: "Bright light; some direct sun",
      watering: "Infrequent; let soil dry completely",
      soil_preference: "Cactus/succulent mix",
      hardiness_zone_min: 9,
      hardiness_zone_max: 12,
      mature_height: "6–18 in",
      mature_width: "6–12 in",
      growth_rate: "Slow",
      maintenance_level: "Very low",
    },
    vine: {
      sunlight: "Full sun to partial shade",
      watering: "Regular; keep soil moist not soggy",
      soil_preference: "Well-draining fertile soil",
      hardiness_zone_min: 6,
      hardiness_zone_max: 10,
      mature_height: "10–20 ft (climbing)",
      mature_width: "3–6 ft spread",
      growth_rate: "Fast",
      maintenance_level: "Moderate",
    },
    grass: {
      sunlight: "Full sun",
      watering: "Regular during establishment",
      soil_preference: "Loamy soil with good drainage",
      hardiness_zone_min: 4,
      hardiness_zone_max: 9,
      mature_height: "2–4 ft",
      mature_width: "Spreading clumps",
      growth_rate: "Fast",
      maintenance_level: "Low",
    },
  };

  const d = defaults[p.type];
  const slug = p.common_name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return {
    id: p.id ?? `species-${slug}`,
    family: p.family ?? "Unknown",
    description:
      p.description ??
      `${p.common_name} (${p.scientific_name}) is a popular ${p.type} valued by home gardeners for its beauty and manageable care requirements.`,
    toxicity: p.toxicity ?? "Varies, verify before pets/children",
    image_url: p.image_url ?? IMG("1416879595882-337324a7f4f9"),
    secondary_images: p.secondary_images ?? [],
    companion_plants:
      p.companion_plants ?? defaultCompanionPlants(p.type, p.common_name),
    pollinator_value: p.pollinator_value ?? defaultPollinatorValue(p.type),
    fruiting_info:
      p.fruiting_info ?? defaultFruitingInfo(p.type, p.common_name),
    flowering_info: p.flowering_info ?? defaultFloweringInfo(p.type),
    source: p.source ?? "plantpal_seed",
    ...d,
    ...p,
  } as PlantSpecies;
}

/** 100+ plant species seed data */
export const PLANT_SPECIES_SEED: PlantSpecies[] = [
  makeSpecies({ common_name: "Meyer Lemon Tree", scientific_name: "Citrus × meyeri", type: "tree", family: "Rutaceae", hardiness_zone_min: 8, hardiness_zone_max: 11, toxicity: "Mild, citrus oils", image_url: IMG("1558618666-fcd25c85cd64") }),
  makeSpecies({ common_name: "Japanese Maple", scientific_name: "Acer palmatum", type: "tree", family: "Sapindaceae", sunlight: "Partial shade", hardiness_zone_min: 5, hardiness_zone_max: 8, image_url: IMG("1592150628122-0e8b6a11a6b0") }),
  makeSpecies({ common_name: "Fiddle Leaf Fig", scientific_name: "Ficus lyrata", type: "indoor", family: "Moraceae", toxicity: "Mildly toxic to pets", image_url: IMG("1593691502-6c263a056f09") }),
  makeSpecies({ common_name: "Bougainvillea", scientific_name: "Bougainvillea spp.", type: "vine", family: "Nyctaginaceae", hardiness_zone_min: 9, hardiness_zone_max: 11, image_url: IMG("1593691502-6c263a056f09") }),
  makeSpecies({ common_name: "Olive Tree", scientific_name: "Olea europaea", type: "tree", family: "Oleaceae", hardiness_zone_min: 8, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Avocado Tree", scientific_name: "Persea americana", type: "tree", family: "Lauraceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Orange Tree", scientific_name: "Citrus sinensis", type: "tree", family: "Rutaceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Lime Tree", scientific_name: "Citrus aurantiifolia", type: "tree", family: "Rutaceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Fig Tree", scientific_name: "Ficus carica", type: "tree", family: "Moraceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Pomegranate", scientific_name: "Punica granatum", type: "shrub", family: "Lythraceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Lavender", scientific_name: "Lavandula angustifolia", type: "herb", family: "Lamiaceae", hardiness_zone_min: 5, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Rosemary", scientific_name: "Salvia rosmarinus", type: "herb", family: "Lamiaceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Basil", scientific_name: "Ocimum basilicum", type: "herb", family: "Lamiaceae", hardiness_zone_min: 10, hardiness_zone_max: 11, maintenance_level: "Low" }),
  makeSpecies({ common_name: "Tomato", scientific_name: "Solanum lycopersicum", type: "vegetable", family: "Solanaceae" }),
  makeSpecies({ common_name: "Rose", scientific_name: "Rosa spp.", type: "flower", family: "Rosaceae", hardiness_zone_min: 4, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Hydrangea", scientific_name: "Hydrangea macrophylla", type: "shrub", family: "Hydrangeaceae", sunlight: "Partial shade", hardiness_zone_min: 5, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Snake Plant", scientific_name: "Dracaena trifasciata", type: "indoor", family: "Asparagaceae", maintenance_level: "Very low", toxicity: "Mildly toxic" }),
  makeSpecies({ common_name: "Monstera", scientific_name: "Monstera deliciosa", type: "indoor", family: "Araceae", toxicity: "Toxic if ingested" }),
  makeSpecies({ common_name: "Pothos", scientific_name: "Epipremnum aureum", type: "indoor", family: "Araceae", maintenance_level: "Very low", toxicity: "Toxic to pets" }),
  makeSpecies({ common_name: "Aloe Vera", scientific_name: "Aloe barbadensis", type: "succulent", family: "Asphodelaceae" }),
  makeSpecies({ common_name: "Jade Plant", scientific_name: "Crassula ovata", type: "succulent", family: "Crassulaceae" }),
  makeSpecies({ common_name: "Bird of Paradise", scientific_name: "Strelitzia reginae", type: "indoor", family: "Strelitziaceae", sunlight: "Bright light" }),
  makeSpecies({ common_name: "Magnolia", scientific_name: "Magnolia grandiflora", type: "tree", family: "Magnoliaceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Crape Myrtle", scientific_name: "Lagerstroemia indica", type: "tree", family: "Lythraceae", hardiness_zone_min: 6, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "California Pepper Tree", scientific_name: "Schinus molle", type: "tree", family: "Anacardiaceae", hardiness_zone_min: 8, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Apple Tree", scientific_name: "Malus domestica", type: "tree", family: "Rosaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Cherry Tree", scientific_name: "Prunus avium", type: "tree", family: "Rosaceae", hardiness_zone_min: 4, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Peach Tree", scientific_name: "Prunus persica", type: "tree", family: "Rosaceae", hardiness_zone_min: 5, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Plum Tree", scientific_name: "Prunus domestica", type: "tree", family: "Rosaceae", hardiness_zone_min: 4, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Pear Tree", scientific_name: "Pyrus communis", type: "tree", family: "Rosaceae", hardiness_zone_min: 4, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Blueberry Bush", scientific_name: "Vaccinium corymbosum", type: "shrub", family: "Ericaceae", sunlight: "Full sun", soil_preference: "Acidic soil", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Raspberry Bush", scientific_name: "Rubus idaeus", type: "shrub", family: "Rosaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Blackberry Bush", scientific_name: "Rubus fruticosus", type: "shrub", family: "Rosaceae" }),
  makeSpecies({ common_name: "Grape Vine", scientific_name: "Vitis vinifera", type: "vine", family: "Vitaceae", hardiness_zone_min: 5, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Kiwi Vine", scientific_name: "Actinidia deliciosa", type: "vine", family: "Actinidiaceae" }),
  makeSpecies({ common_name: "Clematis", scientific_name: "Clematis spp.", type: "vine", family: "Ranunculaceae", sunlight: "Roots shaded, tops in sun" }),
  makeSpecies({ common_name: "Wisteria", scientific_name: "Wisteria sinensis", type: "vine", family: "Fabaceae", hardiness_zone_min: 5, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Hibiscus", scientific_name: "Hibiscus rosa-sinensis", type: "shrub", family: "Malvaceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Gardenia", scientific_name: "Gardenia jasminoides", type: "shrub", family: "Rubiaceae", sunlight: "Morning sun, afternoon shade", hardiness_zone_min: 8, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Azalea", scientific_name: "Rhododendron spp.", type: "shrub", family: "Ericaceae", sunlight: "Partial shade", soil_preference: "Acidic soil" }),
  makeSpecies({ common_name: "Camellia", scientific_name: "Camellia japonica", type: "shrub", family: "Theaceae", sunlight: "Partial shade" }),
  makeSpecies({ common_name: "Boxwood", scientific_name: "Buxus sempervirens", type: "shrub", family: "Buxaceae", maintenance_level: "Moderate" }),
  makeSpecies({ common_name: "Lilac", scientific_name: "Syringa vulgaris", type: "shrub", family: "Oleaceae", hardiness_zone_min: 3, hardiness_zone_max: 7 }),
  makeSpecies({ common_name: "Forsythia", scientific_name: "Forsythia × intermedia", type: "shrub", family: "Oleaceae" }),
  makeSpecies({ common_name: "Peony", scientific_name: "Paeonia lactiflora", type: "flower", family: "Paeoniaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Dahlia", scientific_name: "Dahlia pinnata", type: "flower", family: "Asteraceae" }),
  makeSpecies({ common_name: "Sunflower", scientific_name: "Helianthus annuus", type: "flower", family: "Asteraceae" }),
  makeSpecies({ common_name: "Marigold", scientific_name: "Tagetes erecta", type: "flower", family: "Asteraceae", maintenance_level: "Low" }),
  makeSpecies({ common_name: "Petunia", scientific_name: "Petunia × hybrida", type: "flower", family: "Solanaceae" }),
  makeSpecies({ common_name: "Zinnia", scientific_name: "Zinnia elegans", type: "flower", family: "Asteraceae" }),
  makeSpecies({ common_name: "Pansy", scientific_name: "Viola × wittrockiana", type: "flower", family: "Violaceae", sunlight: "Cool season; partial sun" }),
  makeSpecies({ common_name: "Lettuce", scientific_name: "Lactuca sativa", type: "vegetable", family: "Asteraceae", sunlight: "Partial sun in heat" }),
  makeSpecies({ common_name: "Carrot", scientific_name: "Daucus carota", type: "vegetable", family: "Apiaceae", mature_height: "1 ft foliage" }),
  makeSpecies({ common_name: "Bell Pepper", scientific_name: "Capsicum annuum", type: "vegetable", family: "Solanaceae" }),
  makeSpecies({ common_name: "Cucumber", scientific_name: "Cucumis sativus", type: "vegetable", family: "Cucurbitaceae" }),
  makeSpecies({ common_name: "Zucchini", scientific_name: "Cucurbita pepo", type: "vegetable", family: "Cucurbitaceae" }),
  makeSpecies({ common_name: "Eggplant", scientific_name: "Solanum melongena", type: "vegetable", family: "Solanaceae" }),
  makeSpecies({ common_name: "Strawberry", scientific_name: "Fragaria × ananassa", type: "vegetable", family: "Rosaceae", mature_height: "6–8 in" }),
  makeSpecies({ common_name: "Spinach", scientific_name: "Spinacia oleracea", type: "vegetable", family: "Amaranthaceae", sunlight: "Partial shade OK" }),
  makeSpecies({ common_name: "Kale", scientific_name: "Brassica oleracea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Thyme", scientific_name: "Thymus vulgaris", type: "herb", family: "Lamiaceae" }),
  makeSpecies({ common_name: "Mint", scientific_name: "Mentha spp.", type: "herb", family: "Lamiaceae", watering: "Keep moist; invasive in ground" }),
  makeSpecies({ common_name: "Cilantro", scientific_name: "Coriandrum sativum", type: "herb", family: "Apiaceae" }),
  makeSpecies({ common_name: "Parsley", scientific_name: "Petroselinum crispum", type: "herb", family: "Apiaceae" }),
  makeSpecies({ common_name: "Sage", scientific_name: "Salvia officinalis", type: "herb", family: "Lamiaceae" }),
  makeSpecies({ common_name: "Oregano", scientific_name: "Origanum vulgare", type: "herb", family: "Lamiaceae" }),
  makeSpecies({ common_name: "Chives", scientific_name: "Allium schoenoprasum", type: "herb", family: "Amaryllidaceae" }),
  makeSpecies({ common_name: "ZZ Plant", scientific_name: "Zamioculcas zamiifolia", type: "indoor", family: "Araceae", maintenance_level: "Very low" }),
  makeSpecies({ common_name: "Peace Lily", scientific_name: "Spathiphyllum spp.", type: "indoor", family: "Araceae", sunlight: "Low to bright indirect" }),
  makeSpecies({ common_name: "Rubber Plant", scientific_name: "Ficus elastica", type: "indoor", family: "Moraceae" }),
  makeSpecies({ common_name: "Philodendron", scientific_name: "Philodendron hederaceum", type: "indoor", family: "Araceae", toxicity: "Toxic if ingested" }),
  makeSpecies({ common_name: "Spider Plant", scientific_name: "Chlorophytum comosum", type: "indoor", family: "Asparagaceae", maintenance_level: "Very low" }),
  makeSpecies({ common_name: "Calathea", scientific_name: "Calathea ornata", type: "indoor", family: "Marantaceae", watering: "Consistent moisture; distilled water preferred" }),
  makeSpecies({ common_name: "Anthurium", scientific_name: "Anthurium andraeanum", type: "indoor", family: "Araceae" }),
  makeSpecies({ common_name: "Chinese Evergreen", scientific_name: "Aglaonema commutatum", type: "indoor", family: "Araceae", sunlight: "Low to medium light" }),
  makeSpecies({ common_name: "English Ivy", scientific_name: "Hedera helix", type: "vine", family: "Araliaceae", toxicity: "Toxic to pets" }),
  makeSpecies({ common_name: "Echeveria", scientific_name: "Echeveria elegans", type: "succulent", family: "Crassulaceae" }),
  makeSpecies({ common_name: "Haworthia", scientific_name: "Haworthia fasciata", type: "succulent", family: "Asphodelaceae" }),
  makeSpecies({ common_name: "Agave", scientific_name: "Agave americana", type: "succulent", family: "Asparagaceae", hardiness_zone_min: 8, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Sedum", scientific_name: "Sedum spp.", type: "succulent", family: "Crassulaceae", hardiness_zone_min: 3, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "String of Pearls", scientific_name: "Senecio rowleyanus", type: "succulent", family: "Asteraceae", toxicity: "Toxic to pets" }),
  makeSpecies({ common_name: "Bamboo Palm", scientific_name: "Chamaedorea seifrizii", type: "indoor", family: "Arecaceae" }),
  makeSpecies({ common_name: "Areca Palm", scientific_name: "Dypsis lutescens", type: "indoor", family: "Arecaceae" }),
  makeSpecies({ common_name: "Kentia Palm", scientific_name: "Howea forsteriana", type: "indoor", family: "Arecaceae" }),
  makeSpecies({ common_name: "Weeping Willow", scientific_name: "Salix babylonica", type: "tree", family: "Salicaceae", watering: "High; loves moisture", hardiness_zone_min: 4, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Red Maple", scientific_name: "Acer rubrum", type: "tree", family: "Sapindaceae", hardiness_zone_min: 3, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Oak Tree", scientific_name: "Quercus spp.", type: "tree", family: "Fagaceae", hardiness_zone_min: 4, hardiness_zone_max: 9, mature_height: "40–80 ft" }),
  makeSpecies({ common_name: "Pine Tree", scientific_name: "Pinus spp.", type: "tree", family: "Pinaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Cedar Tree", scientific_name: "Cedrus libani", type: "tree", family: "Pinaceae" }),
  makeSpecies({ common_name: "Palm Tree", scientific_name: "Phoenix canariensis", type: "tree", family: "Arecaceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Dogwood", scientific_name: "Cornus florida", type: "tree", family: "Cornaceae", sunlight: "Partial shade", hardiness_zone_min: 5, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Birch Tree", scientific_name: "Betula pendula", type: "tree", family: "Betulaceae", hardiness_zone_min: 2, hardiness_zone_max: 7 }),
  makeSpecies({ common_name: "Lemon Balm", scientific_name: "Melissa officinalis", type: "herb", family: "Lamiaceae" }),
  makeSpecies({ common_name: "Dill", scientific_name: "Anethum graveolens", type: "herb", family: "Apiaceae" }),
  makeSpecies({ common_name: "Fennel", scientific_name: "Foeniculum vulgare", type: "herb", family: "Apiaceae", mature_height: "3–5 ft" }),
  makeSpecies({ common_name: "Lemongrass", scientific_name: "Cymbopogon citratus", type: "grass", family: "Poaceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Ornamental Grass", scientific_name: "Miscanthus sinensis", type: "grass", family: "Poaceae" }),
  makeSpecies({ common_name: "Blue Fescue", scientific_name: "Festuca glauca", type: "grass", family: "Poaceae", mature_height: "8–12 in" }),
  makeSpecies({ common_name: "Switchgrass", scientific_name: "Panicum virgatum", type: "grass", family: "Poaceae" }),
  makeSpecies({ common_name: "Nandina", scientific_name: "Nandina domestica", type: "shrub", family: "Berberidaceae", toxicity: "Berries toxic" }),
  makeSpecies({ common_name: "Photinia", scientific_name: "Photinia × fraseri", type: "shrub", family: "Rosaceae" }),
  makeSpecies({ common_name: "Viburnum", scientific_name: "Viburnum opulus", type: "shrub", family: "Adoxaceae" }),
  makeSpecies({ common_name: "Spirea", scientific_name: "Spiraea japonica", type: "shrub", family: "Rosaceae" }),
  makeSpecies({ common_name: "Butterfly Bush", scientific_name: "Buddleja davidii", type: "shrub", family: "Scrophulariaceae" }),
  makeSpecies({ common_name: "Geranium", scientific_name: "Pelargonium × hortorum", type: "flower", family: "Geraniaceae" }),
  makeSpecies({ common_name: "Begonia", scientific_name: "Begonia × semperflorens", type: "flower", family: "Begoniaceae", sunlight: "Partial shade" }),
  makeSpecies({ common_name: "Impatiens", scientific_name: "Impatiens walleriana", type: "flower", family: "Balsaminaceae", sunlight: "Shade to partial sun" }),
  makeSpecies({ common_name: "Snapdragon", scientific_name: "Antirrhinum majus", type: "flower", family: "Plantaginaceae" }),
  makeSpecies({ common_name: "Cosmos", scientific_name: "Cosmos bipinnatus", type: "flower", family: "Asteraceae" }),
  makeSpecies({ common_name: "Lantana", scientific_name: "Lantana camara", type: "flower", family: "Verbenaceae", hardiness_zone_min: 8, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Broccoli", scientific_name: "Brassica oleracea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Cauliflower", scientific_name: "Brassica oleracea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Green Bean", scientific_name: "Phaseolus vulgaris", type: "vegetable", family: "Fabaceae" }),
  makeSpecies({ common_name: "Peas", scientific_name: "Pisum sativum", type: "vegetable", family: "Fabaceae", sunlight: "Cool season crop" }),
  makeSpecies({ common_name: "Watermelon", scientific_name: "Citrullus lanatus", type: "vegetable", family: "Cucurbitaceae", mature_height: "Vining" }),
  makeSpecies({ common_name: "Pumpkin", scientific_name: "Cucurbita pepo", type: "vegetable", family: "Cucurbitaceae" }),
  makeSpecies({ common_name: "Sweet Potato", scientific_name: "Ipomoea batatas", type: "vegetable", family: "Convolvulaceae" }),
  makeSpecies({ common_name: "Potato", scientific_name: "Solanum tuberosum", type: "vegetable", family: "Solanaceae" }),
  makeSpecies({ common_name: "Onion", scientific_name: "Allium cepa", type: "vegetable", family: "Amaryllidaceae" }),
  makeSpecies({ common_name: "Garlic", scientific_name: "Allium sativum", type: "vegetable", family: "Amaryllidaceae" }),
  makeSpecies({ common_name: "Corn", scientific_name: "Zea mays", type: "vegetable", family: "Poaceae", mature_height: "6–8 ft" }),
  makeSpecies({ common_name: "Dragon Tree", scientific_name: "Dracaena marginata", type: "indoor", family: "Asparagaceae" }),
  makeSpecies({ common_name: "Cast Iron Plant", scientific_name: "Aspidistra elatior", type: "indoor", family: "Asparagaceae", sunlight: "Low light tolerant" }),
  makeSpecies({ common_name: "Dieffenbachia", scientific_name: "Dieffenbachia seguine", type: "indoor", family: "Araceae", toxicity: "Highly toxic if ingested" }),
  makeSpecies({ common_name: "Boston Fern", scientific_name: "Nephrolepis exaltata", type: "indoor", family: "Nephrolepidaceae", watering: "Keep evenly moist; loves humidity" }),
  makeSpecies({ common_name: "Maidenhair Fern", scientific_name: "Adiantum raddianum", type: "indoor", family: "Pteridaceae", watering: "High humidity required" }),
  makeSpecies({ common_name: "Christmas Cactus", scientific_name: "Schlumbergera truncata", type: "succulent", family: "Cactaceae", watering: "Moderate; not desert-dry" }),
  makeSpecies({ common_name: "Barrel Cactus", scientific_name: "Echinocactus grusonii", type: "succulent", family: "Cactaceae" }),
  makeSpecies({ common_name: "Prickly Pear", scientific_name: "Opuntia ficus-indica", type: "succulent", family: "Cactaceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Passionflower", scientific_name: "Passiflora caerulea", type: "vine", family: "Passifloraceae" }),
  makeSpecies({ common_name: "Morning Glory", scientific_name: "Ipomoea purpurea", type: "vine", family: "Convolvulaceae" }),
  makeSpecies({ common_name: "Honeysuckle", scientific_name: "Lonicera japonica", type: "vine", family: "Caprifoliaceae" }),
  makeSpecies({ common_name: "Trumpet Vine", scientific_name: "Campsis radicans", type: "vine", family: "Bignoniaceae", hardiness_zone_min: 4, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Key Lime Tree", scientific_name: "Citrus × aurantiifolia", type: "tree", family: "Rutaceae", hardiness_zone_min: 9, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Grapefruit Tree", scientific_name: "Citrus × paradisi", type: "tree", family: "Rutaceae" }),
  makeSpecies({ common_name: "Kumquat Tree", scientific_name: "Citrus japonica", type: "tree", family: "Rutaceae", mature_height: "8–15 ft" }),
  makeSpecies({ common_name: "Persimmon Tree", scientific_name: "Diospyros kaki", type: "tree", family: "Ebenaceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Mulberry Tree", scientific_name: "Morus alba", type: "tree", family: "Moraceae" }),
  makeSpecies({ common_name: "Walnut Tree", scientific_name: "Juglans regia", type: "tree", family: "Juglandaceae", hardiness_zone_min: 4, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Almond Tree", scientific_name: "Prunus dulcis", type: "tree", family: "Rosaceae", hardiness_zone_min: 7, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Nectarine Tree", scientific_name: "Prunus persica var. nucipersica", type: "tree", family: "Rosaceae" }),
  makeSpecies({ common_name: "Apricot Tree", scientific_name: "Prunus armeniaca", type: "tree", family: "Rosaceae", hardiness_zone_min: 5, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Loquat Tree", scientific_name: "Eriobotrya japonica", type: "tree", family: "Rosaceae", hardiness_zone_min: 8, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Dragon Fruit Cactus", scientific_name: "Hylocereus undatus", type: "succulent", family: "Cactaceae", hardiness_zone_min: 10, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Lucky Bamboo", scientific_name: "Dracaena sanderiana", type: "indoor", family: "Asparagaceae", sunlight: "Indirect light", watering: "Keep roots in water or moist soil" }),
  makeSpecies({ common_name: "Air Plant", scientific_name: "Tillandsia spp.", type: "indoor", family: "Bromeliaceae", soil_preference: "No soil. Mount or hang", watering: "Mist 2–3× weekly" }),
  makeSpecies({ common_name: "Bromeliad", scientific_name: "Guzmania lingulata", type: "indoor", family: "Bromeliaceae", watering: "Fill central cup; keep moist" }),
  makeSpecies({ common_name: "Orchid", scientific_name: "Phalaenopsis spp.", type: "indoor", family: "Orchidaceae", soil_preference: "Orchid bark mix", watering: "Weekly soak; drain fully" }),
  makeSpecies({ common_name: "Cyclamen", scientific_name: "Cyclamen persicum", type: "flower", family: "Primulaceae", sunlight: "Bright indirect; cool temps" }),
  makeSpecies({ common_name: "Chrysanthemum", scientific_name: "Chrysanthemum morifolium", type: "flower", family: "Asteraceae" }),
  makeSpecies({ common_name: "Tulip", scientific_name: "Tulipa spp.", type: "flower", family: "Liliaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Daffodil", scientific_name: "Narcissus pseudonarcissus", type: "flower", family: "Amaryllidaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Iris", scientific_name: "Iris germanica", type: "flower", family: "Iridaceae" }),
  makeSpecies({ common_name: "Foxglove", scientific_name: "Digitalis purpurea", type: "flower", family: "Plantaginaceae", toxicity: "Highly toxic if ingested" }),
  makeSpecies({ common_name: "Delphinium", scientific_name: "Delphinium elatum", type: "flower", family: "Ranunculaceae", toxicity: "Toxic if ingested" }),
  makeSpecies({ common_name: "Hosta", scientific_name: "Hosta plantaginea", type: "flower", family: "Asparagaceae", sunlight: "Shade to partial shade" }),
  makeSpecies({ common_name: "Daylily", scientific_name: "Hemerocallis fulva", type: "flower", family: "Asphodelaceae", maintenance_level: "Very low" }),
  makeSpecies({ common_name: "Black-Eyed Susan", scientific_name: "Rudbeckia hirta", type: "flower", family: "Asteraceae" }),
  makeSpecies({ common_name: "Coneflower", scientific_name: "Echinacea purpurea", type: "flower", family: "Asteraceae", hardiness_zone_min: 3, hardiness_zone_max: 9 }),
  makeSpecies({ common_name: "Salvia", scientific_name: "Salvia nemorosa", type: "flower", family: "Lamiaceae" }),
  makeSpecies({ common_name: "Verbena", scientific_name: "Verbena bonariensis", type: "flower", family: "Verbenaceae" }),
  makeSpecies({ common_name: "Sweet Alyssum", scientific_name: "Lobularia maritima", type: "flower", family: "Brassicaceae", mature_height: "4–6 in" }),
  makeSpecies({ common_name: "Nasturtium", scientific_name: "Tropaeolum majus", type: "flower", family: "Tropaeolaceae", description: "Edible flowers and leaves." }),
  makeSpecies({ common_name: "Radish", scientific_name: "Raphanus sativus", type: "vegetable", family: "Brassicaceae", mature_height: "6–12 in" }),
  makeSpecies({ common_name: "Beet", scientific_name: "Beta vulgaris", type: "vegetable", family: "Amaranthaceae" }),
  makeSpecies({ common_name: "Turnip", scientific_name: "Brassica rapa", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Cabbage", scientific_name: "Brassica oleracea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Brussels Sprouts", scientific_name: "Brassica oleracea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Asparagus", scientific_name: "Asparagus officinalis", type: "vegetable", family: "Asparagaceae", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Artichoke", scientific_name: "Cynara scolymus", type: "vegetable", family: "Asteraceae", hardiness_zone_min: 7, hardiness_zone_max: 10 }),
  makeSpecies({ common_name: "Okra", scientific_name: "Abelmoschus esculentus", type: "vegetable", family: "Malvaceae", hardiness_zone_min: 5, hardiness_zone_max: 11 }),
  makeSpecies({ common_name: "Swiss Chard", scientific_name: "Beta vulgaris", type: "vegetable", family: "Amaranthaceae" }),
  makeSpecies({ common_name: "Collard Greens", scientific_name: "Brassica oleracea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Mustard Greens", scientific_name: "Brassica juncea", type: "vegetable", family: "Brassicaceae" }),
  makeSpecies({ common_name: "Arugula", scientific_name: "Eruca vesicaria", type: "vegetable", family: "Brassicaceae", mature_height: "6–12 in" }),
  makeSpecies({ common_name: "Leek", scientific_name: "Allium ampeloprasum", type: "vegetable", family: "Amaryllidaceae" }),
  makeSpecies({ common_name: "Shallot", scientific_name: "Allium cepa var. aggregatum", type: "vegetable", family: "Amaryllidaceae" }),
  makeSpecies({ common_name: "Scallion", scientific_name: "Allium fistulosum", type: "vegetable", family: "Amaryllidaceae" }),
  makeSpecies({ common_name: "Celery", scientific_name: "Apium graveolens", type: "vegetable", family: "Apiaceae", watering: "High moisture needs" }),
  makeSpecies({ common_name: "Cantaloupe", scientific_name: "Cucumis melo", type: "vegetable", family: "Cucurbitaceae" }),
  makeSpecies({ common_name: "Honeydew Melon", scientific_name: "Cucumis melo", type: "vegetable", family: "Cucurbitaceae" }),
  makeSpecies({ common_name: "Rhubarb", scientific_name: "Rheum rhabarbarum", type: "vegetable", family: "Polygonaceae", toxicity: "Leaves toxic; stalks edible", hardiness_zone_min: 3, hardiness_zone_max: 8 }),
  makeSpecies({ common_name: "Hops", scientific_name: "Humulus lupulus", type: "vine", family: "Cannabaceae", description: "Fast-growing vine used in brewing." }),
];

export const PLANT_SPECIES: PlantSpecies[] = PLANT_SPECIES_SEED;
