import type { SoilType } from "../types";

export const SOIL_TYPES: SoilType[] = [
  { id: "soil-sandy", name: "Sandy soil", texture: "Coarse, gritty", drainage: "Excellent", ph_min: 5.5, ph_max: 7.0, best_for: "Root vegetables, lavender, rosemary", description: "Light soil that warms quickly and drains fast.", amendments: "Compost, peat moss to retain moisture" },
  { id: "soil-clay", name: "Clay soil", texture: "Fine, sticky when wet", drainage: "Poor", ph_min: 6.0, ph_max: 7.5, best_for: "Roses, brassicas with amendments", description: "Nutrient-rich but compacts easily.", amendments: "Gypsum, sand, organic matter" },
  { id: "soil-loamy", name: "Loamy soil", texture: "Balanced sand/silt/clay", drainage: "Good", ph_min: 6.0, ph_max: 7.0, best_for: "Most garden plants", description: "Ideal all-purpose garden soil.", amendments: "Annual compost top-dressing" },
  { id: "soil-silt", name: "Silt soil", texture: "Smooth, flour-like", drainage: "Moderate", ph_min: 6.0, ph_max: 7.0, best_for: "Grasses, moisture-loving plants", description: "Fertile but can crust when dry.", amendments: "Compost to improve structure" },
  { id: "soil-cactus", name: "Cactus mix", texture: "Gritty, porous", drainage: "Very fast", ph_min: 6.0, ph_max: 7.5, best_for: "Cacti, succulents", description: "Specialty mix with sand and perlite.", amendments: "Extra pumice for heavy waterers" },
  { id: "soil-citrus", name: "Citrus mix", texture: "Loose, well-aerated", drainage: "Excellent", ph_min: 5.5, ph_max: 6.5, best_for: "Citrus trees in containers", description: "Slightly acidic mix for citrus roots.", amendments: "Sulfur if pH rises" },
  { id: "soil-orchid", name: "Orchid bark mix", texture: "Chunky bark", drainage: "Excellent", ph_min: 5.5, ph_max: 6.5, best_for: "Phalaenopsis, epiphytic orchids", description: "Airflow around roots is critical.", amendments: "Replace annually as bark breaks down" },
  { id: "soil-raised", name: "Raised bed mix", texture: "Fluffy, rich", drainage: "Good", ph_min: 6.0, ph_max: 7.0, best_for: "Vegetables, herbs", description: "Blend of topsoil, compost, and aeration.", amendments: "Compost each season" },
  { id: "soil-potting", name: "Potting mix", texture: "Light, peat-based", drainage: "Good", ph_min: 5.5, ph_max: 6.5, best_for: "Container plants, houseplants", description: "Sterile mix for pots and planters.", amendments: "Perlite for extra drainage" },
  { id: "soil-peat", name: "Peat-based mix", texture: "Spongy", drainage: "Moderate", ph_min: 4.5, ph_max: 6.0, best_for: "Acid-loving plants", description: "Holds moisture; acidic pH.", amendments: "Lime to raise pH if needed" },
  { id: "soil-compost", name: "Compost-enriched soil", texture: "Crumbly, dark", drainage: "Good", ph_min: 6.0, ph_max: 7.5, best_for: "Vegetable gardens", description: "High organic matter for fertility.", amendments: "Balanced fertilizer as needed" },
  { id: "soil-acidic", name: "Acidic soil mix", texture: "Fine to medium", drainage: "Moderate", ph_min: 4.5, ph_max: 5.5, best_for: "Blueberries, azaleas, camellias", description: "Low pH for ericaceous plants.", amendments: "Pine bark fines, sulfur" },
  { id: "soil-alkaline", name: "Alkaline soil mix", texture: "Medium", drainage: "Good", ph_min: 7.0, ph_max: 8.0, best_for: "Lavender, clematis", description: "Higher pH for lime-tolerant plants.", amendments: "Avoid peat; use loam and grit" },
  { id: "soil-seed-start", name: "Seed starting mix", texture: "Fine, light", drainage: "Good", ph_min: 5.5, ph_max: 6.5, best_for: "Seedlings, cuttings", description: "Low fertility; fine texture for germination.", amendments: "None until transplant" },
  { id: "soil-palm", name: "Palm potting mix", texture: "Coarse, free-draining", drainage: "Excellent", ph_min: 6.0, ph_max: 7.0, best_for: "Palms indoors and out", description: "Resists compaction in containers.", amendments: "Sand and bark chips" },
  { id: "soil-rose", name: "Rose garden soil", texture: "Rich loam", drainage: "Good", ph_min: 6.0, ph_max: 6.8, best_for: "Roses, flowering shrubs", description: "Deep, fertile beds for heavy feeders.", amendments: "Compost, bone meal" },
  { id: "soil-succulent", name: "Succulent mix", texture: "Gritty", drainage: "Very fast", ph_min: 6.0, ph_max: 7.0, best_for: "Succulents, sedums", description: "Prevents root rot in wet climates.", amendments: "Pumice, coarse sand" },
  { id: "soil-vegetable", name: "Vegetable garden soil", texture: "Loamy", drainage: "Good", ph_min: 6.0, ph_max: 7.0, best_for: "Tomatoes, peppers, squash", description: "Nutrient-rich beds with good tilth.", amendments: "Compost, worm castings" },
  { id: "soil-native", name: "Native soil blend", texture: "Varies by region", drainage: "Varies", ph_min: 5.5, ph_max: 7.5, best_for: "Native and drought-tolerant plants", description: "Mimics local conditions.", amendments: "Minimal — match native habitat" },
  { id: "soil-bonsai", name: "Bonsai soil mix", texture: "Granular, inorganic-heavy", drainage: "Excellent", ph_min: 5.5, ph_max: 6.5, best_for: "Bonsai, miniature trees", description: "Akadama, pumice, lava rock blend.", amendments: "Repot and refresh every 2–3 years" },
];
