import type { SoilType } from "../types";

function soil(
  base: Omit<SoilType, "pros" | "cons" | "water_retention"> & {
    pros: string;
    cons: string;
    water_retention: string;
  }
): SoilType {
  return base;
}

export const SOIL_TYPES: SoilType[] = [
  soil({
    id: "soil-sandy",
    name: "Sandy soil",
    texture: "Coarse, gritty",
    drainage: "Excellent",
    water_retention: "Low — dries quickly",
    ph_min: 5.5,
    ph_max: 7.0,
    best_for: "Root vegetables, lavender, rosemary, carrots",
    description: "Light soil that warms quickly and drains fast.",
    pros: "Easy to work, warms early in spring, good aeration, low compaction",
    cons: "Dries out fast, leaches nutrients, needs frequent watering and feeding",
    amendments: "Compost, peat moss, or coco coir to retain moisture",
  }),
  soil({
    id: "soil-clay",
    name: "Clay soil",
    texture: "Fine, sticky when wet",
    drainage: "Poor",
    water_retention: "High — holds water tightly",
    ph_min: 6.0,
    ph_max: 7.5,
    best_for: "Roses, brassicas with amendments, fruit trees on berms",
    description: "Nutrient-rich but compacts easily when wet.",
    pros: "High mineral content, retains moisture and nutrients, stable structure",
    cons: "Slow drainage, compacts when wet, hard when dry, slow to warm in spring",
    amendments: "Gypsum, coarse sand, and organic matter to improve structure",
  }),
  soil({
    id: "soil-loamy",
    name: "Loamy soil",
    texture: "Balanced sand/silt/clay",
    drainage: "Good",
    water_retention: "Moderate — ideal balance",
    ph_min: 6.0,
    ph_max: 7.0,
    best_for: "Most garden plants, vegetables, shrubs, and trees",
    description: "Ideal all-purpose garden soil with balanced texture.",
    pros: "Best all-around texture, holds moisture and nutrients, easy to cultivate",
    cons: "Can still compact without organic matter; may need pH adjustment for specialists",
    amendments: "Annual compost top-dressing to maintain structure",
  }),
  soil({
    id: "soil-silt",
    name: "Silt soil",
    texture: "Smooth, flour-like",
    drainage: "Moderate",
    water_retention: "Moderate to high",
    ph_min: 6.0,
    ph_max: 7.0,
    best_for: "Grasses, moisture-loving plants, river-bottom gardens",
    description: "Fertile but can crust when dry.",
    pros: "Very fertile, smooth texture, holds nutrients well",
    cons: "Erodes easily, crusts on surface when dry, can waterlog in wet seasons",
    amendments: "Compost and mulch to improve surface structure",
  }),
  soil({
    id: "soil-potting",
    name: "Potting mix",
    texture: "Light, peat-based",
    drainage: "Good",
    water_retention: "Moderate",
    ph_min: 5.5,
    ph_max: 6.5,
    best_for: "Container plants, houseplants, seedlings",
    description: "Sterile lightweight mix for pots and planters.",
    pros: "Lightweight, consistent, good aeration, low weed seeds",
    cons: "Decomposes over time, can repel water when dry, not ideal in-ground",
    amendments: "Perlite or vermiculite for extra drainage; refresh annually in pots",
  }),
  soil({
    id: "soil-cactus",
    name: "Cactus mix",
    texture: "Gritty, porous",
    drainage: "Very fast",
    water_retention: "Very low",
    ph_min: 6.0,
    ph_max: 7.5,
    best_for: "Cacti, succulents, dry-climate container plants",
    description: "Specialty mix with sand, perlite, and minimal organic matter.",
    pros: "Prevents root rot, excellent aeration, mimics desert conditions",
    cons: "Dries very fast, low fertility, wrong choice for thirsty plants",
    amendments: "Extra pumice for heavy waterers or humid climates",
  }),
  soil({
    id: "soil-citrus",
    name: "Citrus mix",
    texture: "Loose, well-aerated",
    drainage: "Excellent",
    water_retention: "Low to moderate",
    ph_min: 5.5,
    ph_max: 6.5,
    best_for: "Citrus trees in containers, acid-loving fruit trees",
    description: "Slightly acidic mix formulated for citrus roots.",
    pros: "Acidic pH, fast drainage, supports healthy citrus root systems",
    cons: "Needs regular feeding; not suited for alkaline-preferring plants",
    amendments: "Sulfur if pH rises above 6.5",
  }),
  soil({
    id: "soil-bonsai",
    name: "Bonsai soil mix",
    texture: "Granular, inorganic-heavy",
    drainage: "Excellent",
    water_retention: "Low — controlled moisture",
    ph_min: 5.5,
    ph_max: 6.5,
    best_for: "Bonsai, miniature trees, shallow containers",
    description: "Akadama, pumice, and lava rock blend for fine root control.",
    pros: "Superior drainage and root pruning response, stable structure, precise watering",
    cons: "Expensive, dries quickly, requires skill to balance water and fertilizer",
    amendments: "Repot and refresh substrate every 2–3 years",
  }),
  soil({
    id: "soil-raised",
    name: "Raised bed mix",
    texture: "Fluffy, rich",
    drainage: "Good",
    water_retention: "Moderate",
    ph_min: 6.0,
    ph_max: 7.0,
    best_for: "Vegetables, herbs, kitchen gardens",
    description: "Blend of topsoil, compost, and aeration materials.",
    pros: "Warmer soil, better drainage than native clay, easy access, fewer compaction issues",
    cons: "Dries faster than in-ground beds, needs annual nutrient replenishment",
    amendments: "Compost and worm castings each season",
  }),
  soil({
    id: "soil-orchid",
    name: "Orchid bark mix",
    texture: "Chunky bark",
    drainage: "Excellent",
    water_retention: "Low",
    ph_min: 5.5,
    ph_max: 6.5,
    best_for: "Phalaenopsis, epiphytic orchids",
    description: "Airflow around roots is critical for epiphytic orchids.",
    pros: "Mimics natural epiphytic habitat, excellent root airflow",
    cons: "Breaks down in 1–2 years, requires repotting schedule",
    amendments: "Replace annually as bark decomposes",
  }),
  soil({
    id: "soil-peat",
    name: "Peat-based mix",
    texture: "Spongy",
    drainage: "Moderate",
    water_retention: "High",
    ph_min: 4.5,
    ph_max: 6.0,
    best_for: "Acid-loving plants, blueberries, camellias",
    description: "Holds moisture with naturally acidic pH.",
    pros: "Excellent moisture retention, acidic for ericaceous plants",
    cons: "Environmental concerns with peat harvesting; can become hydrophobic when dry",
    amendments: "Lime to raise pH if needed; consider peat-free alternatives",
  }),
  soil({
    id: "soil-compost",
    name: "Compost-enriched soil",
    texture: "Crumbly, dark",
    drainage: "Good",
    water_retention: "Moderate to high",
    ph_min: 6.0,
    ph_max: 7.5,
    best_for: "Vegetable gardens, new beds, soil improvement",
    description: "High organic matter for fertility and soil biology.",
    pros: "Builds soil life, improves structure, gentle slow-release nutrients",
    cons: "Can be too rich alone for some natives; verify compost is fully finished",
    amendments: "Blend with native soil rather than planting in pure compost",
  }),
  soil({
    id: "soil-acidic",
    name: "Acidic soil mix",
    texture: "Fine to medium",
    drainage: "Moderate",
    water_retention: "Moderate",
    ph_min: 4.5,
    ph_max: 5.5,
    best_for: "Blueberries, azaleas, camellias, rhododendrons",
    description: "Low pH mix for acid-preferring ornamentals and edibles.",
    pros: "Correct pH for ericaceous plants, good structure with pine bark",
    cons: "Wrong pH for most vegetables; requires monitoring",
    amendments: "Pine bark fines, sulfur to maintain acidity",
  }),
  soil({
    id: "soil-alkaline",
    name: "Alkaline soil mix",
    texture: "Medium",
    drainage: "Good",
    water_retention: "Moderate",
    ph_min: 7.0,
    ph_max: 8.0,
    best_for: "Lavender, clematis, Mediterranean herbs",
    description: "Higher pH for lime-tolerant plants.",
    pros: "Suited to Mediterranean and chalk-loving species",
    cons: "Blocks iron uptake for acid-lovers; not for blueberries or azaleas",
    amendments: "Avoid peat; use loam, grit, and lime if needed",
  }),
  soil({
    id: "soil-seed-start",
    name: "Seed starting mix",
    texture: "Fine, light",
    drainage: "Good",
    water_retention: "Moderate",
    ph_min: 5.5,
    ph_max: 6.5,
    best_for: "Seedlings, cuttings, propagation",
    description: "Low fertility fine texture for germination.",
    pros: "Fine texture for seed contact, sterile, lightweight",
    cons: "Not enough nutrients for long-term growth; transplant quickly",
    amendments: "None until transplant — feed after first true leaves",
  }),
  soil({
    id: "soil-palm",
    name: "Palm potting mix",
    texture: "Coarse, free-draining",
    drainage: "Excellent",
    water_retention: "Moderate",
    ph_min: 6.0,
    ph_max: 7.0,
    best_for: "Palms indoors and outdoors",
    description: "Resists compaction in containers.",
    pros: "Stable structure, supports palm root systems, resists compaction",
    cons: "Needs regular magnesium and manganese for palm health",
    amendments: "Sand and bark chips; palm-specific fertilizer",
  }),
  soil({
    id: "soil-rose",
    name: "Rose garden soil",
    texture: "Rich loam",
    drainage: "Good",
    water_retention: "Moderate",
    ph_min: 6.0,
    ph_max: 6.8,
    best_for: "Roses, flowering shrubs, heavy feeders",
    description: "Deep, fertile beds for repeat-blooming roses.",
    pros: "Rich and fertile, good drainage, supports heavy feeding schedule",
    cons: "Requires ongoing fertilization and disease monitoring",
    amendments: "Compost, bone meal at planting",
  }),
  soil({
    id: "soil-succulent",
    name: "Succulent mix",
    texture: "Gritty",
    drainage: "Very fast",
    water_retention: "Very low",
    ph_min: 6.0,
    ph_max: 7.0,
    best_for: "Succulents, sedums, echeveria",
    description: "Prevents root rot in wet climates.",
    pros: "Fast drainage, prevents rot, suitable for shallow roots",
    cons: "Needs more frequent light feeding in growing season",
    amendments: "Pumice, coarse sand, pine bark",
  }),
  soil({
    id: "soil-vegetable",
    name: "Vegetable garden soil",
    texture: "Loamy",
    drainage: "Good",
    water_retention: "Moderate",
    ph_min: 6.0,
    ph_max: 7.0,
    best_for: "Tomatoes, peppers, squash, leafy greens",
    description: "Nutrient-rich beds with good tilth for edibles.",
    pros: "High fertility, good structure, supports intensive planting",
    cons: "Depletes nutrients quickly; needs crop rotation and compost",
    amendments: "Compost, worm castings each season",
  }),
  soil({
    id: "soil-native",
    name: "Native soil blend",
    texture: "Varies by region",
    drainage: "Varies",
    water_retention: "Varies",
    ph_min: 5.5,
    ph_max: 7.5,
    best_for: "Native and drought-tolerant plants",
    description: "Mimics local conditions for low-maintenance landscapes.",
    pros: "Low inputs once established, supports local ecology",
    cons: "Not suited to thirsty exotic plants; varies widely by source",
    amendments: "Minimal — match plants to native habitat",
  }),
];
