import type { ProductRecommendation } from "./types";

export const MOCK_PRODUCTS: ProductRecommendation[] = [
  {
    id: "prod-meyer-lemon",
    name: "Meyer Lemon (dwarf standard)",
    category: "plants",
    description: "Compact citrus tree ideal for patios and small yards in zones 8–11.",
    bestFor: "Home orchards, beginner fruit growers, full sun patios",
    priceRange: "$35–$85 (3–5 gal nursery)",
    whyItFits: "Productive at a manageable size; grafted trees fruit sooner than seed-grown.",
    whatToAvoid: "Root-bound pots, yellow leaves at purchase, unlabeled rootstock",
    imageUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
  },
  {
    id: "prod-hass-avocado",
    name: "Hass Avocado (5 gal)",
    category: "plants",
    description: "Most common home-garden avocado with excellent flavor.",
    bestFor: "Mild climates, frost-free yards, avocado enthusiasts",
    priceRange: "$45–$120 (5 gal)",
    whyItFits: "Type A flower pattern. Pair with Fuerte or Lamb for better fruit set.",
    whatToAvoid: "Wilted leaves, cracked trunk, trees with no graft union visible",
  },
  {
    id: "prod-lavender",
    name: "English Lavender",
    category: "plants",
    description: "Drought-tolerant perennial for full sun and low water yards.",
    bestFor: "Low-maintenance landscapes, pollinator edges, Mediterranean yards",
    priceRange: "$8–$18 (1 gal)",
    whyItFits: "Thrives on neglect once established; excellent for dry climates.",
    whatToAvoid: "Overwatered nursery stock, leggy plants with no new growth",
  },
  {
    id: "prod-citrus-soil",
    name: "Citrus & Avocado Planting Mix",
    category: "soil",
    description: "Fast-draining, slightly acidic blend for citrus and avocados.",
    bestFor: "Citrus trees, avocados, container planting",
    priceRange: "$12–$22 (1.5 cu ft bag)",
    whyItFits: "Proper drainage prevents root rot. Critical for citrus in containers.",
    whatToAvoid: "Heavy topsoil, moisture-control mixes that stay wet, unlabeled generic soil",
  },
  {
    id: "prod-raised-bed-mix",
    name: "Raised Bed Vegetable Mix",
    category: "soil",
    description: "Compost-rich blend for edibles and cut flowers.",
    bestFor: "Vegetable gardens, raised beds, seasonal color",
    priceRange: "$8–$16 (1 cu ft)",
    whyItFits: "Balanced organic matter supports roots without compaction.",
    whatToAvoid: "Pure compost without aeration, soil with unfinished manure smell",
  },
  {
    id: "prod-citrus-fert",
    name: "Citrus & Avocado Fertilizer (8-4-8)",
    category: "fertilizer",
    description: "Slow-release granular with micronutrients including iron and zinc.",
    bestFor: "Citrus trees, avocados, fruiting shrubs",
    priceRange: "$14–$28 (4 lb bag)",
    whyItFits: "Matches N-P-K needs of heavy feeders without burning roots when applied correctly.",
    whatToAvoid: "High-nitrogen lawn fertilizer on citrus, feeding stressed or dry plants",
  },
  {
    id: "prod-avocado-fert",
    name: "Avocado & Subtropical Plant Food",
    category: "fertilizer",
    description: "Formulated for avocados with zinc and manganese support.",
    bestFor: "Hass and Fuerte avocados, subtropical fruit trees",
    priceRange: "$16–$32 (5 lb)",
    whyItFits: "Addresses common avocado deficiencies that cause leaf tip burn.",
    whatToAvoid: "Quick-release urea-heavy feeds, fertilizing during heat stress",
  },
  {
    id: "prod-air-pot",
    name: "Air-Pot Container (15–20 gal)",
    category: "pots",
    description: "Root-pruning container that prevents circling roots.",
    bestFor: "Citrus, avocados, long-term container trees",
    priceRange: "$25–$55",
    whyItFits: "Healthier root structure than smooth-sided nursery pots.",
    whatToAvoid: "Undersized pots for mature trees, pots without drainage holes",
  },
  {
    id: "prod-drip-kit",
    name: "Adjustable Drip Irrigation Kit",
    category: "irrigation",
    description: "Starter kit with timer, emitters, and tubing for 10–20 plants.",
    bestFor: "Fruit trees, raised beds, consistent watering schedules",
    priceRange: "$35–$75",
    whyItFits: "Deep, infrequent watering beats daily sprinkles for tree health.",
    whatToAvoid: "Overhead sprinklers for disease-prone foliage, cheap timers with no rain pause",
  },
  {
    id: "prod-felco-pruner",
    name: "Bypass Pruner (Felco-style)",
    category: "pruning_tools",
    description: "Sharp bypass pruner for clean cuts on live wood up to ¾ inch.",
    bestFor: "Roses, citrus, shrubs, general pruning",
    priceRange: "$25–$65",
    whyItFits: "Clean cuts heal faster; replaceable blades last years.",
    whatToAvoid: "Anvil pruners on live branches, dull blades that crush stems",
  },
  {
    id: "prod-insecticidal-soap",
    name: "Insecticidal Soap Concentrate",
    category: "pest_control",
    description: "Contact spray for aphids, mites, and soft-bodied pests.",
    bestFor: "Citrus, houseplants, organic gardens",
    priceRange: "$10–$18",
    whyItFits: "Low toxicity when used as directed; effective on sap-suckers.",
    whatToAvoid: "Spraying in full midday sun, mixing stronger than label rates",
  },
  {
    id: "prod-bonsai-shears",
    name: "Beginner Bonsai Shear Set",
    category: "bonsai_supplies",
    description: "Concave cutter + knob cutter + leaf scissors starter trio.",
    bestFor: "First bonsai, juniper and ficus refinement",
    priceRange: "$30–$70",
    whyItFits: "Right tools prevent bark tearing. Essential for clean bonsai cuts.",
    whatToAvoid: "Kitchen scissors, rusty tools, oversized cutters on small trees",
  },
  {
    id: "prod-bonsai-wire",
    name: "Aluminum Bonsai Wire Assortment",
    category: "bonsai_supplies",
    description: "Mixed gauge anodized aluminum wire for branch shaping.",
    bestFor: "Wiring deciduous and broadleaf bonsai",
    priceRange: "$12–$24",
    whyItFits: "Aluminum is forgiving for beginners; remove before it cuts in.",
    whatToAvoid: "Copper wire on first trees, leaving wire on past growing season",
  },
  {
    id: "prod-shade-hosta",
    name: "Hosta Collection (shade)",
    category: "plants",
    description: "Shade-loving foliage plants for north-facing beds and patios.",
    bestFor: "Full shade borders, under trees, low-light patios",
    priceRange: "$10–$22 (1 gal)",
    whyItFits: "Reliable color where sun lovers fail; minimal maintenance.",
    whatToAvoid: "Sun-scorched leaves at nursery (wrong placement history)",
  },
  {
    id: "prod-snake-plant",
    name: "Snake Plant (low maintenance)",
    category: "plants",
    description: "Indoor survivor tolerant of irregular watering.",
    bestFor: "Beginners, offices, low-light corners",
    priceRange: "$8–$25",
    whyItFits: "Hard to kill; teaches watering restraint.",
    whatToAvoid: "Soggy soil, oversized decorative pots with no drainage",
  },
];

export function getProductById(id: string): ProductRecommendation | undefined {
  return MOCK_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(
  category: ProductRecommendation["category"]
): ProductRecommendation[] {
  return MOCK_PRODUCTS.filter((p) => p.category === category);
}
